import type { JSX } from 'react'

export function Footer (): JSX.Element {
  return (
    <footer className="footer">
      <p className="footer-copyright">© 2026. Generated by AI.</p>
    </footer>
  )
}
